// Weekly Performance Digest routes — read the digests generated by the opt-in
// weeklyDigest cron.

const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth');
const asyncHandler = require('../middleware/asyncHandler');
const { sendSuccess, sendError } = require('../utils/response');
const { clampInt } = require('../utils/pagination');
const PerformanceDigest = require('../models/PerformanceDigest');

const uidOf = (req) => String(req.user._id || req.user.id);

/** GET /api/digest/latest — the caller's most recent digest. */
router.get('/latest', auth, asyncHandler(async (req, res) => {
  const digest = await PerformanceDigest.findOne({ userId: uidOf(req) })
    .sort({ createdAt: -1 })
    .lean();
  sendSuccess(res, 'Latest digest retrieved', 200, { digest: digest || null });
}));

/** GET /api/digest?limit=&skip= — the caller's digest history (paginated). */
router.get('/', auth, asyncHandler(async (req, res) => {
  const limit = clampInt(req.query.limit, 12, 52, 1);
  const skip = clampInt(req.query.skip, 0, 100000, 0);
  const digests = await PerformanceDigest.find({ userId: uidOf(req) })
    .sort({ createdAt: -1 })
    .skip(skip)
    .limit(limit)
    .lean();
  sendSuccess(res, 'Digests retrieved', 200, { digests });
}));

/** GET /api/digest/:id — a specific digest, scoped to the caller. */
router.get('/:id', auth, asyncHandler(async (req, res) => {
  const digest = await PerformanceDigest.findOne({ _id: req.params.id, userId: uidOf(req) }).lean();
  if (!digest) return sendError(res, 'Digest not found', 404);
  sendSuccess(res, 'Digest retrieved', 200, { digest });
}));

/** POST /api/digest/:id/read — mark a digest read (scoped to the caller). */
router.post('/:id/read', auth, asyncHandler(async (req, res) => {
  const r = await PerformanceDigest.updateOne(
    { _id: req.params.id, userId: uidOf(req) },
    { $set: { read: true, readAt: new Date() } },
  );
  if (!r.matchedCount) return sendError(res, 'Digest not found', 404);
  sendSuccess(res, 'Digest marked read', 200, { read: true });
}));

module.exports = router;
