// PerformanceDigest — a persisted weekly performance recap for one user.
// Generated by the opt-in digestCron and served via /api/digest. Keyed by a
// String userId (matching ScheduledPost/Content) so the digest joins the same
// identity the analytics aggregates use.

const mongoose = require('mongoose');

const performanceDigestSchema = new mongoose.Schema({
  userId: { type: String, required: true, index: true },
  periodStart: { type: Date, required: true },
  periodEnd: { type: Date, required: true },

  summary: {
    trend: { type: String, enum: ['up', 'down', 'stable', 'new'], default: 'new' },
    changePct: { type: Number, default: null }, // week-over-week eng-rate %, null if no prior
    totalEngagement: { type: Number, default: 0 },
    totalReach: { type: Number, default: 0 },
    avgEngagementRate: { type: Number, default: 0 },
    postCount: { type: Number, default: 0 },
  },

  // Top posts this window.
  wins: [{
    id: String,
    platform: String,
    engagement: Number,
    reach: Number,
    postedAt: Date,
  }],

  // Post activity/engagement grouped by platform this window.
  platformTrends: [{
    platform: String,
    posts: Number,
    engagement: Number,
  }],

  // Up to 3 next-best actions (from the growth/next-best engine; empty until the
  // learning loop has enough data — we never fabricate).
  nextActions: [{
    source: String,      // 'next-best' | 'baseline'
    title: String,
    detail: String,
  }],

  hasData: { type: Boolean, default: false },
  read: { type: Boolean, default: false },
  readAt: { type: Date, default: null },
  createdAt: { type: Date, default: Date.now },
});

// One digest per user per period; newest-first reads for /latest.
performanceDigestSchema.index({ userId: 1, createdAt: -1 });
performanceDigestSchema.index({ userId: 1, periodStart: 1 }, { unique: true });

module.exports = mongoose.models.PerformanceDigest
  || mongoose.model('PerformanceDigest', performanceDigestSchema);
