#!/bin/bash

# Instructions for adding Sentry DSN to Render.com
# This script provides copy-paste instructions

SENTRY_DSN="https://a400da46f531219b7ce6f78a9d5cb6ff@o4510623214731264.ingest.de.sentry.io/4510629716033616"

echo "🔧 Sentry DSN Setup Instructions"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📋 Copy-Paste Instructions for Render.com"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to: https://dashboard.render.com"
echo "2. Click your service: click-platform"
echo "3. Click 'Environment' tab"
echo "4. Click 'Add Environment Variable'"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 Environment Variable Details:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Key:"
echo "SENTRY_DSN"
echo ""
echo "Value (copy this entire line):"
echo "$SENTRY_DSN"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ After Adding:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Click 'Save Changes'"
echo "2. Render.com will auto-redeploy (2-3 minutes)"
echo "3. Check logs for: '✅ Sentry initialized'"
echo "4. Go to Sentry dashboard to verify"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 Verify Setup:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After deployment, check:"
echo "1. Render.com logs → Look for Sentry messages"
echo "2. Sentry dashboard → Issues tab (should be empty initially)"
echo "3. Health endpoint → Should show Sentry status"
echo ""

