#!/usr/bin/env node
/**
 * Autonomous Assignment Generator
 * Run: npm run assign 1  (or node scripts/assign.js 1)
 * Outputs ASSIGNMENT_READY.md with copy-paste content for ROADMAP_STATUS + GitHub issue
 */

const fs = require('fs');
const path = require('path');

const BANK_PATH = path.join(__dirname, 'assignments-bank.json');
const OUTPUT_PATH = path.join(__dirname, '..', 'ASSIGNMENT_READY.md');
const ISSUE_URL = 'https://github.com/Droze-svj/click-platform/issues/new';

function loadBank() {
  const data = fs.readFileSync(BANK_PATH, 'utf8');
  return JSON.parse(data);
}

function buildIssueBody(assignment) {
  const tasks = assignment.tasks.map(t => `- [ ] ${t}`).join('\n');
  const files = assignment.files.map(f => `- ${f}`).join('\n');
  return `## Goal
${assignment.title}

## Tasks
${tasks}

## Source
${assignment.source} - ${assignment.section}

## Files to check
${files}

## Notes
- Effort: ~${assignment.effort}
- Branch: \`${assignment.branch}\`
- Don't change: auth flow, existing schema unless needed`;
}

function buildRoadmapRow(assignment, issueNum = null) {
  const link = issueNum
    ? `[#${issueNum}](https://github.com/Droze-svj/click-platform/issues/${issueNum})`
    : '*Create issue first → replace with #XX*';
  return `| ${assignment.id} | ${assignment.title} | ${link} | ${assignment.effort} | — |`;
}

function buildCollaboratorMessage(assignment, issueNum = null) {
  const issueUrl = issueNum
    ? `https://github.com/Droze-svj/click-platform/issues/${issueNum}`
    : 'https://github.com/Droze-svj/click-platform/issues/XX  ← replace XX with issue #';
  return `**New assignment:** #${assignment.id} — ${assignment.title}
Issue: ${issueUrl}
Branch: \`${assignment.branch}\`
Effort: ~${assignment.effort}`;
}

function main() {
  const bank = loadBank();
  const assignments = bank.assignments;

  const arg = process.argv[2];
  let assignment;

  if (arg) {
    const id = parseInt(arg, 10);
    assignment = assignments.find(a => a.id === id);
    if (!assignment) {
      console.error(`\n❌ Assignment #${arg} not found. Use 1-${assignments.length}\n`);
      process.exit(1);
    }
  } else {
    // Interactive: show list
    console.log('\n📋 Available assignments:\n');
    assignments.forEach(a => {
      console.log(`  ${a.id}. ${a.title} (${a.effort})`);
    });
    console.log(`\nUsage: npm run assign <number>\nExample: npm run assign 1\n`);
    process.exit(0);
  }

  const issueBody = buildIssueBody(assignment);
  const roadmapRow = buildRoadmapRow(assignment, null);  // User fills in # after creating
  const collaboratorMsg = buildCollaboratorMessage(assignment, null);

  const output = `# Assignment Ready — #${assignment.id}: ${assignment.title}

> **Generated by** \`npm run assign ${assignment.id}\`
> **Next:** 1) Create issue below → 2) Copy ROADMAP_STATUS row → 3) Send message to collaborator

---

## 1️⃣ Create GitHub Issue

**URL:** ${ISSUE_URL}

**Title:** \`[Roadmap] ${assignment.title}\`

**Body:** (copy below)
\`\`\`
${issueBody}
\`\`\`

**Then:** Assign collaborator, submit → note the issue number (e.g. #42)

---

## 2️⃣ Add to ROADMAP_STATUS.md (Next Up table)

Copy this row. After creating the issue, replace \`XX\` with the issue number:

${roadmapRow}

---

## 3️⃣ Message to Send Collaborator

(copy after you have the issue number)

\`\`\`
${collaboratorMsg}
\`\`\`

---

## Quick Reference

| Field | Value |
|-------|-------|
| Branch | \`${assignment.branch}\` |
| Effort | ${assignment.effort} |
| Source | ${assignment.source} |
`;

  fs.writeFileSync(OUTPUT_PATH, output, 'utf8');
  console.log(`\n✅ ASSIGNMENT_READY.md created\n`);
  console.log(`   Assignment #${assignment.id}: ${assignment.title}`);
  console.log(`   Branch: ${assignment.branch}`);
  console.log(`\n   Open ASSIGNMENT_READY.md and follow the 3 steps.\n`);
}

main();
