#!/bin/bash

# Best Practices Production Setup Script
# This script sets up Click with recommended best practices and optimal configurations

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║  Click - Best Practices Production Setup                ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

# Best Practice Recommendations
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Recommended Best Practices:${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${GREEN}✅ Hosting:${NC} DigitalOcean Droplet (Ubuntu 22.04, 2GB RAM minimum)"
echo -e "${GREEN}✅ Database:${NC} MongoDB Atlas (Free tier M0 or paid M10+)"
echo -e "${GREEN}✅ Cache:${NC} Redis Cloud (Free tier 30MB or paid)"
echo -e "${GREEN}✅ Storage:${NC} AWS S3 with CloudFront CDN"
echo -e "${GREEN}✅ SSL:${NC} Let's Encrypt (free, auto-renewal)"
echo -e "${GREEN}✅ Monitoring:${NC} Sentry + PM2 + Uptime monitoring"
echo -e "${GREEN}✅ Process Manager:${NC} PM2 with cluster mode"
echo ""

read -p "Continue with best practices setup? (Y/n): " continue_setup
if [[ $continue_setup =~ ^[Nn]$ ]]; then
    echo "Setup cancelled."
    exit 0
fi

# Generate secure secrets
echo -e "${BLUE}Generating secure secrets...${NC}"
JWT_SECRET=$(openssl rand -base64 32 2>/dev/null || echo "change-this-secret-$(date +%s)")
SESSION_SECRET=$(openssl rand -base64 32 2>/dev/null || echo "change-this-secret-$(date +%s)")

# Create optimized .env.production with best practices
echo -e "${BLUE}Creating optimized .env.production...${NC}"

cat > .env.production << 'ENVEOF'
# ============================================
# Click Production Environment - Best Practices
# Generated by setup-best-practices.sh
# ============================================

# ============================================
# SERVER CONFIGURATION
# ============================================
NODE_ENV=production
PORT=5001
FRONTEND_URL=https://your-domain.com
APP_URL=https://your-domain.com

# ============================================
# DATABASE - MongoDB Atlas (Recommended)
# ============================================
# Replace with your MongoDB Atlas connection string
# Format: mongodb+srv://username:password@cluster.mongodb.net/click?retryWrites=true&w=majority
MONGODB_URI=mongodb+srv://username:password@cluster.mongodb.net/click?retryWrites=true&w=majority

# ============================================
# SECURITY - Auto-generated secure secrets
# ============================================
ENVEOF

cat >> .env.production << EOF
JWT_SECRET=$JWT_SECRET
JWT_EXPIRES_IN=7d
SESSION_SECRET=$SESSION_SECRET

# ============================================
# REDIS CACHING - Redis Cloud (Recommended)
# ============================================
# Replace with your Redis Cloud connection string
# Format: redis://username:password@host:port
REDIS_URL=redis://localhost:6379

# ============================================
# AWS S3 STORAGE (Recommended)
# ============================================
# Replace with your AWS credentials
AWS_ACCESS_KEY_ID=your-aws-access-key-id
AWS_SECRET_ACCESS_KEY=your-aws-secret-access-key
AWS_S3_BUCKET=click-production
AWS_REGION=us-east-1
AWS_CLOUDFRONT_URL=https://your-cloudfront-url.cloudfront.net

# ============================================
# OAUTH - LinkedIn
# ============================================
LINKEDIN_CLIENT_ID=your-linkedin-client-id
LINKEDIN_CLIENT_SECRET=your-linkedin-client-secret
LINKEDIN_CALLBACK_URL=https://your-domain.com/api/oauth/linkedin/callback

# ============================================
# OAUTH - Facebook (also used for Instagram)
# ============================================
FACEBOOK_APP_ID=your-facebook-app-id
FACEBOOK_APP_SECRET=your-facebook-app-secret
FACEBOOK_CALLBACK_URL=https://your-domain.com/api/oauth/facebook/callback

# ============================================
# OAUTH - TikTok
# ============================================
TIKTOK_CLIENT_KEY=your-tiktok-client-key
TIKTOK_CLIENT_SECRET=your-tiktok-client-secret
TIKTOK_CALLBACK_URL=https://your-domain.com/api/oauth/tiktok/callback

# ============================================
# OAUTH - YouTube
# ============================================
YOUTUBE_CLIENT_ID=your-youtube-client-id
YOUTUBE_CLIENT_SECRET=your-youtube-client-secret
YOUTUBE_CALLBACK_URL=https://your-domain.com/api/oauth/youtube/callback

# ============================================
# OAUTH - Twitter/X
# ============================================
TWITTER_CLIENT_ID=your-twitter-client-id
TWITTER_CLIENT_SECRET=your-twitter-client-secret
TWITTER_CALLBACK_URL=https://your-domain.com/api/oauth/twitter/callback

# ============================================
# AI MODELS - OpenAI (Primary)
# ============================================
OPENAI_API_KEY=sk-your-openai-api-key

# ============================================
# MONITORING & ERROR TRACKING - Sentry
# ============================================
SENTRY_DSN=https://your-sentry-dsn@sentry.io/project-id

# ============================================
# EMAIL SERVICE (Optional)
# ============================================
SMTP_HOST=smtp.sendgrid.net
SMTP_PORT=587
SMTP_USER=apikey
SMTP_PASS=your-sendgrid-api-key
SMTP_FROM=noreply@your-domain.com

# ============================================
# RATE LIMITING - Best Practice Settings
# ============================================
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX=100
RATE_LIMIT_SKIP_SUCCESSFUL_REQUESTS=true

# ============================================
# LOGGING - Production Settings
# ============================================
LOG_LEVEL=info
LOG_FORMAT=json

# ============================================
# FEATURE FLAGS
# ============================================
ENABLE_ANALYTICS=true
ENABLE_MONITORING=true
ENABLE_CACHING=true
ENABLE_FREE_AI_MODELS=true
ENABLE_CDN=true

# ============================================
# PERFORMANCE OPTIMIZATION
# ============================================
ENABLE_COMPRESSION=true
ENABLE_HTTP2=true
MAX_REQUEST_SIZE=50mb
REQUEST_TIMEOUT=30000

# ============================================
# SECURITY HEADERS
# ============================================
ENABLE_CORS=true
CORS_ORIGIN=https://your-domain.com
ENABLE_HELMET=true
ENABLE_RATE_LIMITING=true

# ============================================
# CLUSTER MODE (PM2)
# ============================================
CLUSTER_MODE=true
CLUSTER_INSTANCES=max
EOF

echo -e "${GREEN}✅ .env.production created with best practices${NC}"

# Create optimized PM2 ecosystem config
echo -e "${BLUE}Creating optimized PM2 configuration...${NC}"

cat > ecosystem.production.config.js << 'PM2EOF'
module.exports = {
  apps: [{
    name: 'click-api',
    script: './server/index.js',
    instances: 'max', // Use all CPU cores
    exec_mode: 'cluster',
    env_production: {
      NODE_ENV: 'production',
      PORT: 5001
    },
    // Best practice settings
    max_memory_restart: '1G', // Restart if memory exceeds 1GB
    min_uptime: '10s', // Minimum uptime before considering stable
    max_restarts: 10, // Maximum restarts in 1 minute
    restart_delay: 4000, // Delay between restarts
    // Logging
    error_file: './logs/pm2-error.log',
    out_file: './logs/pm2-out.log',
    log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
    merge_logs: true,
    // Advanced settings
    kill_timeout: 5000,
    wait_ready: true,
    listen_timeout: 10000,
    // Auto restart on file changes (disabled in production)
    watch: false,
    // Ignore specific files
    ignore_watch: ['node_modules', 'logs', '.git'],
  }]
};
PM2EOF

echo -e "${GREEN}✅ PM2 configuration optimized${NC}"

# Create optimized Nginx configuration
echo -e "${BLUE}Creating optimized Nginx configuration...${NC}"

cat > nginx.production.conf << 'NGINXEOF'
# Click Production Nginx Configuration - Best Practices

# Upstream backend
upstream click_backend {
    least_conn; # Load balancing method
    server 127.0.0.1:5001 max_fails=3 fail_timeout=30s;
    keepalive 32;
}

# Rate limiting zones
limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;
limit_req_zone $binary_remote_addr zone=oauth_limit:10m rate=5r/s;

# Main server block
server {
    listen 80;
    server_name your-domain.com www.your-domain.com;
    
    # Redirect HTTP to HTTPS
    return 301 https://$server_name$request_uri;
}

server {
    listen 443 ssl http2;
    server_name your-domain.com www.your-domain.com;

    # SSL Configuration (Let's Encrypt)
    ssl_certificate /etc/letsencrypt/live/your-domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/your-domain.com/privkey.pem;
    
    # SSL Best Practices
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_stapling on;
    ssl_stapling_verify on;

    # Security Headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Gzip Compression
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types text/plain text/css text/xml text/javascript application/json application/javascript application/xml+rss application/rss+xml font/truetype font/opentype application/vnd.ms-fontobject image/svg+xml;

    # Client body size
    client_max_body_size 100M;
    client_body_buffer_size 128k;

    # Timeouts
    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;

    # Frontend (Next.js)
    location / {
        root /var/www/click/client/.next;
        try_files $uri $uri/ /index.html;
        
        # Cache static assets
        location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|woff2|ttf|eot)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
        }
    }

    # API endpoints
    location /api {
        limit_req zone=api_limit burst=20 nodelay;
        
        proxy_pass http://click_backend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
    }

    # OAuth endpoints (stricter rate limiting)
    location /api/oauth {
        limit_req zone=oauth_limit burst=10 nodelay;
        
        proxy_pass http://click_backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Health check (no rate limiting)
    location /api/health {
        proxy_pass http://click_backend;
        access_log off;
    }

    # Static files
    location /static {
        alias /var/www/click/client/public;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Deny access to hidden files
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
NGINXEOF

echo -e "${GREEN}✅ Nginx configuration optimized${NC}"

# Create deployment script with best practices
echo -e "${BLUE}Creating optimized deployment script...${NC}"

cat > scripts/deploy-best-practices.sh << 'DEPLOYEOF'
#!/bin/bash

# Best Practices Deployment Script
set -e

echo "🚀 Deploying Click with best practices..."

# 1. Pre-deployment checks
echo "📋 Running pre-deployment checks..."
npm run validate:production
npm run test:oauth:structure || echo "⚠️  OAuth structure check skipped"
npm test || echo "⚠️  Tests skipped"

# 2. Build frontend
echo "🏗️  Building frontend..."
cd client
npm ci
npm run build
cd ..

# 3. Install production dependencies
echo "📦 Installing production dependencies..."
npm ci --production

# 4. Database migration
echo "🗄️  Running database migrations..."
npm run deploy:migrate || echo "⚠️  Migrations skipped"

# 5. Restart PM2
echo "🔄 Restarting application..."
pm2 restart ecosystem.production.config.js --update-env || pm2 start ecosystem.production.config.js

# 6. Save PM2 configuration
pm2 save

# 7. Verify deployment
echo "✅ Verifying deployment..."
sleep 5
curl -f http://localhost:5001/api/health || echo "⚠️  Health check failed"

echo "🎉 Deployment complete!"
DEPLOYEOF

chmod +x scripts/deploy-best-practices.sh

echo -e "${GREEN}✅ Deployment script created${NC}"

# Create monitoring setup script
echo -e "${BLUE}Creating monitoring configuration...${NC}"

cat > scripts/setup-monitoring-best-practices.sh << 'MONITOREOF'
#!/bin/bash

# Best Practices Monitoring Setup

echo "📊 Setting up monitoring with best practices..."

# PM2 Monitoring
echo "Setting up PM2 monitoring..."
pm2 install pm2-logrotate
pm2 set pm2-logrotate:max_size 10M
pm2 set pm2-logrotate:retain 7
pm2 set pm2-logrotate:compress true

# Setup PM2 web monitoring (optional)
# pm2 web

echo "✅ Monitoring configured"
MONITOREOF

chmod +x scripts/setup-monitoring-best-practices.sh

echo -e "${GREEN}✅ Monitoring setup script created${NC}"

# Summary
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Best Practices Setup Complete!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${CYAN}Files Created:${NC}"
echo "  ✅ .env.production (with secure secrets)"
echo "  ✅ ecosystem.production.config.js (PM2 cluster mode)"
echo "  ✅ nginx.production.conf (optimized Nginx)"
echo "  ✅ scripts/deploy-best-practices.sh"
echo "  ✅ scripts/setup-monitoring-best-practices.sh"
echo ""
echo -e "${CYAN}Next Steps:${NC}"
echo "  1. Update .env.production with your actual credentials"
echo "  2. Update nginx.production.conf with your domain"
echo "  3. Run: npm run validate:production"
echo "  4. Deploy: bash scripts/deploy-best-practices.sh"
echo ""


