#!/bin/bash

# Free Tier Setup Script
# Configures Click for 100% free hosting and services

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║  Click - Free Tier Configuration                       ║${NC}"
echo -e "${CYAN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}Free Tier Services:${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${GREEN}✅ Hosting:${NC} Railway.app (free tier - $5 credit/month)"
echo -e "${GREEN}✅ Database:${NC} MongoDB Atlas M0 (512MB free forever)"
echo -e "${GREEN}✅ Cache:${NC} Redis Cloud (30MB free forever)"
echo -e "${GREEN}✅ Storage:${NC} AWS S3 (5GB free, first 12 months)"
echo -e "${GREEN}✅ SSL:${NC} Let's Encrypt (free forever)"
echo -e "${GREEN}✅ Monitoring:${NC} Sentry (5K events/month free)"
echo -e "${GREEN}✅ Uptime:${NC} UptimeRobot (50 monitors free)"
echo ""
echo -e "${YELLOW}Total Cost: $0/month (100% Free)${NC}"
echo ""

read -p "Continue with free tier setup? (Y/n): " continue_setup
if [[ $continue_setup =~ ^[Nn]$ ]]; then
    echo "Setup cancelled."
    exit 0
fi

# Generate secure secrets
echo -e "${BLUE}Generating secure secrets...${NC}"
JWT_SECRET=$(openssl rand -base64 32 2>/dev/null || echo "change-this-secret-$(date +%s)")
SESSION_SECRET=$(openssl rand -base64 32 2>/dev/null || echo "change-this-secret-$(date +%s)")

# Create free tier .env.production
echo -e "${BLUE}Creating free tier .env.production...${NC}"

cat > .env.production << 'ENVEOF'
# ============================================
# Click Free Tier Production Environment
# Generated by setup-free-tier.sh
# All services configured for free tiers
# ============================================

# ============================================
# SERVER CONFIGURATION
# ============================================
NODE_ENV=production
PORT=5001
# Update with your Railway.app URL or custom domain
FRONTEND_URL=https://your-app.railway.app
APP_URL=https://your-app.railway.app

# ============================================
# DATABASE - MongoDB Atlas FREE (M0)
# ============================================
# Get free M0 cluster at: https://www.mongodb.com/cloud/atlas
# Free tier: 512MB storage, shared cluster
MONGODB_URI=mongodb+srv://username:password@cluster.mongodb.net/click?retryWrites=true&w=majority

# ============================================
# SECURITY - Auto-generated secure secrets
# ============================================
ENVEOF

cat >> .env.production << EOF
JWT_SECRET=$JWT_SECRET
JWT_EXPIRES_IN=7d
SESSION_SECRET=$SESSION_SECRET

# ============================================
# REDIS CACHING - Redis Cloud FREE (30MB)
# ============================================
# Get free tier at: https://redis.com/try-free/
# Free tier: 30MB storage
REDIS_URL=redis://username:password@host:port

# ============================================
# AWS S3 STORAGE - FREE TIER (First 12 months)
# ============================================
# Free tier: 5GB storage, 20K GET requests/month
# After 12 months: ~\$0.023/GB/month
# Alternative: Use Cloudflare R2 (10GB free/month, no egress)
AWS_ACCESS_KEY_ID=your-aws-access-key-id
AWS_SECRET_ACCESS_KEY=your-aws-secret-access-key
AWS_S3_BUCKET=click-free-tier
AWS_REGION=us-east-1
# Note: Skip CloudFront to save costs (use direct S3 URLs)

# ============================================
# OAUTH - LinkedIn (Free)
# ============================================
LINKEDIN_CLIENT_ID=your-linkedin-client-id
LINKEDIN_CLIENT_SECRET=your-linkedin-client-secret
LINKEDIN_CALLBACK_URL=https://your-app.railway.app/api/oauth/linkedin/callback

# ============================================
# OAUTH - Facebook (Free, also used for Instagram)
# ============================================
FACEBOOK_APP_ID=your-facebook-app-id
FACEBOOK_APP_SECRET=your-facebook-app-secret
FACEBOOK_CALLBACK_URL=https://your-app.railway.app/api/oauth/facebook/callback

# ============================================
# OAUTH - TikTok (Free)
# ============================================
TIKTOK_CLIENT_KEY=your-tiktok-client-key
TIKTOK_CLIENT_SECRET=your-tiktok-client-secret
TIKTOK_CALLBACK_URL=https://your-app.railway.app/api/oauth/tiktok/callback

# ============================================
# OAUTH - YouTube (Free)
# ============================================
YOUTUBE_CLIENT_ID=your-youtube-client-id
YOUTUBE_CLIENT_SECRET=your-youtube-client-secret
YOUTUBE_CALLBACK_URL=https://your-app.railway.app/api/oauth/youtube/callback

# ============================================
# OAUTH - Twitter/X (Free)
# ============================================
TWITTER_CLIENT_ID=your-twitter-client-id
TWITTER_CLIENT_SECRET=your-twitter-client-secret
TWITTER_CALLBACK_URL=https://your-app.railway.app/api/oauth/twitter/callback

# ============================================
# AI MODELS - OpenAI (Pay-as-you-go)
# ============================================
# Note: OpenAI is not free, but you can use free alternatives
# See: FREE_AI_MODELS.md for free AI options
OPENAI_API_KEY=sk-your-openai-api-key

# ============================================
# MONITORING - Sentry FREE (5K events/month)
# ============================================
# Get free tier at: https://sentry.io/signup/
# Free tier: 5,000 events/month
SENTRY_DSN=https://your-sentry-dsn@sentry.io/project-id

# ============================================
# EMAIL SERVICE - Free Options
# ============================================
# Option 1: SendGrid (100 emails/day free)
# Option 2: Mailgun (5,000 emails/month free)
# Option 3: Resend (3,000 emails/month free)
SMTP_HOST=smtp.sendgrid.net
SMTP_PORT=587
SMTP_USER=apikey
SMTP_PASS=your-sendgrid-api-key
SMTP_FROM=noreply@your-domain.com

# ============================================
# RATE LIMITING - Free Tier Optimized
# ============================================
RATE_LIMIT_WINDOW_MS=900000
RATE_LIMIT_MAX=50
RATE_LIMIT_SKIP_SUCCESSFUL_REQUESTS=true

# ============================================
# LOGGING - Production Settings
# ============================================
LOG_LEVEL=info
LOG_FORMAT=json

# ============================================
# FEATURE FLAGS - Free Tier Optimized
# ============================================
ENABLE_ANALYTICS=true
ENABLE_MONITORING=true
ENABLE_CACHING=true
ENABLE_FREE_AI_MODELS=true
ENABLE_CDN=false
# CDN disabled to save costs (use direct S3 URLs)

# ============================================
# PERFORMANCE OPTIMIZATION
# ============================================
ENABLE_COMPRESSION=true
ENABLE_HTTP2=true
MAX_REQUEST_SIZE=25mb
# Reduced from 50mb for free tier
REQUEST_TIMEOUT=30000

# ============================================
# SECURITY HEADERS
# ============================================
ENABLE_CORS=true
CORS_ORIGIN=https://your-app.railway.app
ENABLE_HELMET=true
ENABLE_RATE_LIMITING=true

# ============================================
# FREE TIER LIMITS
# ============================================
# MongoDB Atlas: 512MB storage limit
# Redis Cloud: 30MB storage limit
# AWS S3: 5GB free (first 12 months)
# Sentry: 5,000 events/month
# Monitor these limits and set up alerts
EOF

echo -e "${GREEN}✅ .env.production created for free tier${NC}"

# Create Railway.app configuration
echo -e "${BLUE}Creating Railway.app configuration...${NC}"

cat > railway.json << 'RAILWAYEOF'
{
  "$schema": "https://railway.app/railway.schema.json",
  "build": {
    "builder": "NIXPACKS",
    "buildCommand": "npm install && cd client && npm install && npm run build"
  },
  "deploy": {
    "startCommand": "npm start",
    "restartPolicyType": "ON_FAILURE",
    "restartPolicyMaxRetries": 10
  }
}
RAILWAYEOF

echo -e "${GREEN}✅ Railway.app configuration created${NC}"

# Create Render.com configuration (alternative)
echo -e "${BLUE}Creating Render.com configuration...${NC}"

cat > render.yaml << 'RENDEREOF'
services:
  - type: web
    name: click-api
    env: node
    buildCommand: npm install && cd client && npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
    healthCheckPath: /api/health
RENDEREOF

echo -e "${GREEN}✅ Render.com configuration created${NC}"

# Create free tier deployment guide
cat > FREE_TIER_DEPLOYMENT.md << 'GUIDEEOF'
# 🆓 Free Tier Deployment Guide

## Quick Start

### 1. Setup Free Services

1. **MongoDB Atlas** (Free):
   - Sign up: https://www.mongodb.com/cloud/atlas
   - Create M0 cluster (free)
   - Get connection string

2. **Redis Cloud** (Free):
   - Sign up: https://redis.com/try-free/
   - Create free database (30MB)
   - Get connection string

3. **AWS S3** (Free for 12 months):
   - Sign up: https://aws.amazon.com/
   - Create S3 bucket
   - Get credentials

4. **Sentry** (Free):
   - Sign up: https://sentry.io/signup/
   - Create project
   - Get DSN

### 2. Deploy to Railway.app

1. Sign up: https://railway.app/
2. New Project → Deploy from GitHub
3. Select your repository
4. Add environment variables from .env.production
5. Deploy!

### 3. Alternative: Render.com

1. Sign up: https://render.com/
2. New Web Service
3. Connect GitHub
4. Use render.yaml configuration
5. Add environment variables
6. Deploy!

## Free Tier Limits

- **MongoDB**: 512MB storage
- **Redis**: 30MB storage
- **AWS S3**: 5GB free (first 12 months)
- **Sentry**: 5,000 events/month
- **Railway**: $5 credit/month

## Monitoring Free Tier Usage

Set up alerts for:
- MongoDB storage approaching 512MB
- Redis memory approaching 30MB
- Sentry events approaching 5,000/month
- AWS S3 storage approaching 5GB

GUIDEEOF

echo -e "${GREEN}✅ Free tier deployment guide created${NC}"

# Summary
echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✅ Free Tier Setup Complete!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${CYAN}Files Created:${NC}"
echo "  ✅ .env.production (free tier optimized)"
echo "  ✅ railway.json (Railway.app config)"
echo "  ✅ render.yaml (Render.com config)"
echo "  ✅ FREE_TIER_DEPLOYMENT.md (deployment guide)"
echo ""
echo -e "${CYAN}Next Steps:${NC}"
echo "  1. Sign up for free services (see FREE_TIER_DEPLOYMENT.md)"
echo "  2. Update .env.production with your credentials"
echo "  3. Deploy to Railway.app or Render.com"
echo "  4. Monitor free tier usage"
echo ""
echo -e "${YELLOW}💰 Total Cost: \$0/month (100% Free)${NC}"
echo ""


