apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: click-frontend-hpa
  namespace: click-production
  labels:
    app: click-frontend
    component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: click-frontend
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: 1000m  # 1000 requests per second per pod
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 4
        periodSeconds: 60
      selectPolicy: Max
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: click-backend-hpa
  namespace: click-production
  labels:
    app: click-backend
    component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: click-backend
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: 500m  # 500 requests per second per pod
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 30
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 3
        periodSeconds: 60
      selectPolicy: Max
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: click-worker-hpa
  namespace: click-production
  labels:
    app: click-worker
    component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: click-worker
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: External
    external:
      metric:
        name: queue_length
        selector:
          matchLabels:
            queue: video-processing
      target:
        type: AverageValue
        averageValue: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 50
        periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 200
        periodSeconds: 60
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-autoscaler-config
  namespace: kube-system
data:
  config.yaml: |
    ---
    autoscalingGroups:
    - name: click-frontend-asg
      maxSize: 20
      minSize: 3
    - name: click-backend-asg
      maxSize: 15
      minSize: 3
    - name: click-worker-asg
      maxSize: 10
      minSize: 2
    scaleDown:
      enabled: true
      unneededTime: 10m
      unreadyTime: 20m
      utilizationThreshold: 0.4
      delayAfterAdd: 10m
      delayAfterDelete: 2m
      delayAfterFailure: 3m
    scaleUp:
      enabled: true
      delayAfterAdd: 10s
      delayAfterDelete: 5m
      delayAfterFailure: 3m
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: click-high-priority
value: 1000000
globalDefault: false
description: "High priority class for Click critical services"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: click-medium-priority
value: 100000
globalDefault: false
description: "Medium priority class for Click standard services"
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: click-low-priority
value: 10000
globalDefault: false
description: "Low priority class for Click background services"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: click-production
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    pid /run/nginx.pid;

    events {
        worker_connections 1024;
        use epoll;
        multi_accept on;
    }

    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        # Logging
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for" '
                        'rt=$request_time uct="$upstream_connect_time" '
                        'uht="$upstream_header_time" urt="$upstream_response_time"';

        access_log /var/log/nginx/access.log main;

        # Performance optimizations
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        keepalive_requests 100;
        reset_timedout_connection on;
        client_body_timeout 12;
        client_header_timeout 12;
        send_timeout 10;

        # Gzip compression
        gzip on;
        gzip_vary on;
        gzip_min_length 1024;
        gzip_proxied expired no-cache no-store private must-revalidate auth;
        gzip_comp_level 6;
        gzip_types
            text/plain
            text/css
            text/xml
            text/javascript
            application/javascript
            application/xml+rss
            application/json
            application/ld+json
            application/manifest+json
            application/x-font-ttf
            application/x-font-opentype
            application/x-font-truetype
            font/opentype
            font/truetype
            image/svg+xml;

        # Rate limiting
        limit_req_zone $binary_remote_addr zone=api:10m rate=100r/s;
        limit_req_zone $binary_remote_addr zone=uploads:10m rate=10r/m;
        limit_req_zone $binary_remote_addr zone=general:10m rate=50r/s;

        # Security headers
        add_header X-Frame-Options DENY always;
        add_header X-Content-Type-Options nosniff always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy strict-origin-when-cross-origin always;
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.click-app.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: blob: https:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://api.click-app.com wss://api.click-app.com https://cdn.click-app.com; frame-ancestors 'none';" always;
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

        # Upstream servers
        upstream click_frontend {
            least_conn;
            server click-frontend-1:3000 weight=10 max_fails=3 fail_timeout=30s;
            server click-frontend-2:3000 weight=10 max_fails=3 fail_timeout=30s;
            server click-frontend-3:3000 weight=10 max_fails=3 fail_timeout=30s;
            keepalive 32;
        }

        upstream click_backend {
            least_conn;
            server click-backend-1:5001 weight=5 max_fails=3 fail_timeout=30s;
            server click-backend-2:5001 weight=5 max_fails=3 fail_timeout=30s;
            server click-backend-3:5001 weight=5 max_fails=3 fail_timeout=30s;
            keepalive 16;
        }

        upstream click_api {
            least_conn;
            server click-backend-1:5001 weight=3 max_fails=3 fail_timeout=30s;
            server click-backend-2:5001 weight=3 max_fails=3 fail_timeout=30s;
            server click-backend-3:5001 weight=3 max_fails=3 fail_timeout=30s;
            keepalive 8;
        }

        # Frontend server
        server {
            listen 80 default_server;
            server_name _;
            return 301 https://$server_name$request_uri;
        }

        server {
            listen 443 ssl http2;
            server_name click-app.com www.click-app.com;

            # SSL configuration
            ssl_certificate /etc/nginx/ssl/fullchain.pem;
            ssl_certificate_key /etc/nginx/ssl/privkey.pem;
            ssl_protocols TLSv1.2 TLSv1.3;
            ssl_ciphers ECDHE-RSA-AES256-GCM-SHA512:DHE-RSA-AES256-GCM-SHA512:ECDHE-RSA-AES256-GCM-SHA384;
            ssl_prefer_server_ciphers off;
            ssl_session_cache shared:SSL:10m;
            ssl_session_timeout 10m;

            # Frontend routes
            location / {
                limit_req zone=general burst=100 nodelay;
                proxy_pass http://click_frontend;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Forwarded-Host $server_name;
                proxy_cache_bypass $http_upgrade;
                proxy_read_timeout 86400;
                proxy_send_timeout 86400;

                # Caching for static assets
                location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
                    expires 1y;
                    add_header Cache-Control "public, immutable";
                    add_header X-Cache-Status $upstream_cache_status;
                    proxy_pass http://click_frontend;
                }
            }

            # API routes with stricter limits
            location /api/ {
                limit_req zone=api burst=50 nodelay;
                client_max_body_size 50M;
                proxy_pass http://click_api;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_cache_bypass $http_upgrade;
                proxy_read_timeout 300;
                proxy_send_timeout 300;
            }

            # Upload routes
            location /uploads/ {
                limit_req zone=uploads burst=5 nodelay;
                client_max_body_size 100M;
                proxy_pass http://click_backend;
                proxy_http_version 1.1;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_read_timeout 600;
                proxy_send_timeout 600;
            }

            # Health checks
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }

            # Monitoring endpoint
            location /metrics {
                allow 10.0.0.0/8;
                allow 172.16.0.0/12;
                allow 192.168.0.0/16;
                deny all;
                stub_status on;
                access_log off;
            }
        }
    }


